"""Render `docs/benchmarks.md` from the bench phases + per-stage DB stats."""

from __future__ import annotations

from datetime import UTC, datetime


def _ms(x) -> str:
    return "—" if x is None else f"{float(x):.2f}"


def _by_name(phases: list[dict]) -> dict[str, dict]:
    return {p["name"]: p for p in phases}


def _table(headers: list[str], rows: list[list]) -> str:
    line = "| " + " | ".join(headers) + " |"
    sep = "| " + " | ".join("---" for _ in headers) + " |"
    body = "\n".join("| " + " | ".join(str(c) for c in r) + " |" for r in rows)
    return "\n".join([line, sep, body])


_METHODOLOGY = """\
## Methodology

Measured against a **deterministic mock upstream** (`bench/mock_upstream.py`) that emits a
canned OpenAI SSE stream — no tokens, no external network — so the numbers isolate the
gateway's own behavior and are reproducible at zero cost. Load is generated by **k6** (Go;
the generator isn't the bottleneck). The bench runs a **fully isolated** gateway instance
(separate port `:4300`, its own SQLite DB, `provider=mock`) so it never perturbs a running
gateway instance.

Two measurement sources:
- **k6 (client-side):** end-to-end latency percentiles, throughput, and — because k6 buffers
  the body — `http_req_waiting` ≈ **time-to-first-byte (SSE TTFB)** while `http_req_duration`
  ≈ **full-stream time**, so streaming overhead = duration − TTFB.
- **agentgate audit DB (server-side):** the gateway records per-request stage latency
  (`latency_total_ms`, `latency_upstream_ms`, `latency_inject_ms`); we percentile those for
  the **per-stage decomposition** k6 can't see inside the process.

**Gateway overhead** is the gateway's own per-request work, measured **server-side** from the
audit DB (`gateway internal` = total − upstream). It is small enough that the client-side
`gateway p99 − baseline p99` subtraction is dominated by the loopback baseline's own run-to-run
variance — it swings widely between runs and can even come out negative — so the server-side
per-stage table is the authoritative overhead figure.
"""


def render(phases: list[dict], per_stage: dict) -> str:
    gen = datetime.now(UTC).strftime("%Y-%m-%d %H:%M UTC")
    by = _by_name(phases)
    parts: list[str] = []

    parts.append("---\ntitle: agentgate\n---\n\n# Benchmarks — agentgate gateway\n")
    parts.append(f"> Generated {gen} by `uv run python -m bench.run`. "
                 "Deterministic mock upstream; single-box (one uvicorn worker), loopback.\n")
    parts.append(_METHODOLOGY)

    # End-to-end table.
    parts.append("\n## End-to-end latency under load\n")
    parts.append("All times in **ms**. Offered load is k6's target arrival rate; achieved "
                 "rps is what completed.\n")
    rows = []
    for name in ("gateway_rate_50", "gateway_rate_100", "gateway_rate_200",
                 "gateway_large_100", "baseline_rate_100"):
        p = by.get(name)
        if not p:
            continue
        r = p["result"]
        label = name.replace("gateway_", "gw ").replace("baseline_", "baseline ").replace("_", " ")
        rows.append([
            label, p.get("rate", "—"), r["rps"], f"{r['fail_rate']:.2%}",
            _ms(r["dur_p50"]), _ms(r["dur_p90"]), _ms(r["dur_p95"]), _ms(r["dur_p99"]),
            _ms(r["dur_max"]), _ms(r["ttfb_p99"]),
        ])
    parts.append(_table(
        ["phase", "offered rps", "achieved rps", "fail%",
         "p50", "p90", "p95", "p99", "max", "TTFB p99"],
        rows,
    ))
    parts.append("\n*`gw large` adds a 4 KB `role:\"tool\"` block to exercise the inbound "
                 "injection scan; compare it to `gw 100` to see the scan's marginal cost.*\n")

    # Gateway overhead — authoritative figure is server-side; the end-to-end subtraction is
    # noise-dominated at sub-ms overhead and can come out negative.
    gi = per_stage.get("gateway_internal_ms", {})
    gw, base = by.get("gateway_rate_100"), by.get("baseline_rate_100")
    if gi.get("count"):
        parts.append("\n## Gateway overhead\n")
        parts.append(f"The gateway's own added latency — measured server-side and isolated from "
                     f"the upstream — is **{_ms(gi['p95'])} ms p95 ({_ms(gi['p99'])} ms p99)** "
                     f"across {gi['count']} requests (parse + inject-scan + spend check + SSE tee "
                     "+ fire-and-forget audit dispatch). This is the floor the proxy adds "
                     "regardless of which guard backend is enabled.\n")
        if (gw and base and gw["result"]["dur_p99"] is not None
                and base["result"]["dur_p99"] is not None):
            oh = gw["result"]["dur_p99"] - base["result"]["dur_p99"]
            parts.append(
                f"> The client-side end-to-end subtraction — gateway p99 "
                f"**{_ms(gw['result']['dur_p99'])} ms** minus direct-to-mock baseline p99 "
                f"**{_ms(base['result']['dur_p99'])} ms** → **{_ms(oh)} ms** — is **not** a "
                "reliable overhead measure here: the gateway's cost is below the loopback "
                "baseline's run-to-run variance, so this difference is noise-dominated and can "
                "come out negative. Use the per-stage decomposition below.\n")

    # Streaming overhead.
    if gw and gw["result"]["dur_p99"] is not None and gw["result"]["ttfb_p99"] is not None:
        stream_oh = gw["result"]["dur_p99"] - gw["result"]["ttfb_p99"]
        parts.append("\n## Streaming overhead\n")
        parts.append(f"At 100 rps, p99 TTFB **{_ms(gw['result']['ttfb_p99'])} ms** vs. "
                     f"full-stream p99 **{_ms(gw['result']['dur_p99'])} ms** → the SSE body "
                     f"(deterministic short completion) adds **≈ {_ms(stream_oh)} ms** of "
                     "stream-receive time. The gateway never buffers the stream — chunks are "
                     "teed through as they arrive.\n")

    # Per-stage decomposition.
    parts.append("\n## Per-stage latency (server-side, all gateway requests)\n")
    parts.append(f"From the gateway's audit DB ({per_stage['rows']} requests). `inject` is the "
                 "inbound scan; `upstream` is the mock's stream time; `gateway internal` = "
                 "total − upstream (parse + scan + spend + tee + dispatch).\n")
    sr = []
    for key, label in [("inject_ms", "inject scan"), ("upstream_ms", "upstream (mock)"),
                       ("gateway_internal_ms", "gateway internal"), ("total_ms", "total")]:
        s = per_stage.get(key, {})
        if s.get("count"):
            sr.append([label, s["count"], _ms(s["p50"]), _ms(s["p95"]), _ms(s["p99"]), _ms(s["max"])])
    parts.append(_table(["stage", "n", "p50", "p95", "p99", "max"], sr))

    # Deferred.
    parts.append("\n## Deferred\n")
    parts.append("- **Routing overhead** — the sensitivity classifier + rules-table router "
                 "are not yet implemented; this harness leaves a slot for a router-on/off "
                 "comparison (and a `latency_classify_ms` / `latency_route_ms` per-stage row) "
                 "once they exist.\n")
    parts.append("- **Real local-model upstream** — the mock is the reproducible baseline; a "
                 "real omlx/llama.cpp run is an optional later comparison once a model is pulled.\n")
    parts.append("\n> Caveats: single machine, one uvicorn worker, loopback (no real network "
                 "RTT). The **server-side per-stage** figures are the gateway's own cost; the "
                 "end-to-end percentiles include upstream + transport and are not end-user "
                 "latency to a cloud provider.\n")

    return "\n".join(parts) + "\n"
